/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SigHelper__factory } from "./SigHelper__factory";
export { TDocDeployer__factory } from "./TDocDeployer__factory";
