/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITradeTrustTokenBurnable,
  ITradeTrustTokenBurnableInterface,
} from "../../../contracts/interfaces/ITradeTrustTokenBurnable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITradeTrustTokenBurnable__factory {
  static readonly abi = _abi;
  static createInterface(): ITradeTrustTokenBurnableInterface {
    return new utils.Interface(_abi) as ITradeTrustTokenBurnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITradeTrustTokenBurnable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITradeTrustTokenBurnable;
  }
}
