/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITradeTrustTokenRestorable,
  ITradeTrustTokenRestorableInterface,
} from "../../../contracts/interfaces/ITradeTrustTokenRestorable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "restore",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITradeTrustTokenRestorable__factory {
  static readonly abi = _abi;
  static createInterface(): ITradeTrustTokenRestorableInterface {
    return new utils.Interface(_abi) as ITradeTrustTokenRestorableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITradeTrustTokenRestorable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITradeTrustTokenRestorable;
  }
}
