/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  RegistryAccessErrors,
  RegistryAccessErrorsInterface,
} from "../../../contracts/interfaces/RegistryAccessErrors";

const _abi = [
  {
    inputs: [],
    name: "InvalidAdminAddress",
    type: "error",
  },
];

export class RegistryAccessErrors__factory {
  static readonly abi = _abi;
  static createInterface(): RegistryAccessErrorsInterface {
    return new utils.Interface(_abi) as RegistryAccessErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RegistryAccessErrors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as RegistryAccessErrors;
  }
}
