/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TitleEscrowFactoryErrors,
  TitleEscrowFactoryErrorsInterface,
} from "../../../contracts/interfaces/TitleEscrowFactoryErrors";

const _abi = [
  {
    inputs: [],
    name: "CreateCallerNotContract",
    type: "error",
  },
];

export class TitleEscrowFactoryErrors__factory {
  static readonly abi = _abi;
  static createInterface(): TitleEscrowFactoryErrorsInterface {
    return new utils.Interface(_abi) as TitleEscrowFactoryErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TitleEscrowFactoryErrors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TitleEscrowFactoryErrors;
  }
}
