/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RegistryAccess__factory } from "./RegistryAccess__factory";
export { SBTUpgradeable__factory } from "./SBTUpgradeable__factory";
export { TradeTrustSBT__factory } from "./TradeTrustSBT__factory";
export { TradeTrustTokenBase__factory } from "./TradeTrustTokenBase__factory";
export { TradeTrustTokenBaseURI__factory } from "./TradeTrustTokenBaseURI__factory";
export { TradeTrustTokenBurnable__factory } from "./TradeTrustTokenBurnable__factory";
export { TradeTrustTokenMintable__factory } from "./TradeTrustTokenMintable__factory";
export { TradeTrustTokenRestorable__factory } from "./TradeTrustTokenRestorable__factory";
